name: Continuous Benchmarking with Bencher
on:
  push:
    branches:
      - main

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    env:
      BENCHER_PROJECT: rcf3
      BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: bencherdev/bencher@v0.6.6
      - run: bencher run --adapter rust_criterion "cargo bench --bench comparison_bench"
